/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as ChallengesIndexRouteImport } from './routes/challenges.index'
import { Route as ChallengesIdRouteImport } from './routes/challenges.$id'
import { Route as ChallengesNewRouteImport } from './routes/challenges.new'
import { Route as DashboardCitizenRouteImport } from './routes/dashboard.citizen'
import { Route as GovernmentDashboardRouteImport } from './routes/government.dashboard'
import { Route as IndustryDashboardRouteImport } from './routes/industry.dashboard'
import { Route as IssuesIdRouteImport } from './routes/issues.$id'
import { Route as UniversityDashboardRouteImport } from './routes/university.dashboard'
import { Route as WorkerDashboardRouteImport } from './routes/worker.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIdRoute = ChallengesIdRouteImport.update({
  id: '/challenges/$id',
  path: '/challenges/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesNewRoute = ChallengesNewRouteImport.update({
  id: '/challenges/new',
  path: '/challenges/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCitizenRoute = DashboardCitizenRouteImport.update({
  id: '/dashboard/citizen',
  path: '/dashboard/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentDashboardRoute = GovernmentDashboardRouteImport.update({
  id: '/government/dashboard',
  path: '/government/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryDashboardRoute = IndustryDashboardRouteImport.update({
  id: '/industry/dashboard',
  path: '/industry/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIdRoute = IssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityDashboardRoute = UniversityDashboardRouteImport.update({
  id: '/university/dashboard',
  path: '/university/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerDashboardRoute = WorkerDashboardRouteImport.update({
  id: '/worker/dashboard',
  path: '/worker/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/challenges/new': typeof ChallengesNewRoute
  '/dashboard/citizen': typeof DashboardCitizenRoute
  '/government/dashboard': typeof GovernmentDashboardRoute
  '/industry/dashboard': typeof IndustryDashboardRoute
  '/issues/$id': typeof IssuesIdRoute
  '/university/dashboard': typeof UniversityDashboardRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/challenges/new': typeof ChallengesNewRoute
  '/dashboard/citizen': typeof DashboardCitizenRoute
  '/government/dashboard': typeof GovernmentDashboardRoute
  '/industry/dashboard': typeof IndustryDashboardRoute
  '/issues/$id': typeof IssuesIdRoute
  '/university/dashboard': typeof UniversityDashboardRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/challenges': typeof ChallengesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/challenges/new': typeof ChallengesNewRoute
  '/dashboard/citizen': typeof DashboardCitizenRoute
  '/government/dashboard': typeof GovernmentDashboardRoute
  '/industry/dashboard': typeof IndustryDashboardRoute
  '/issues/$id': typeof IssuesIdRoute
  '/university/dashboard': typeof UniversityDashboardRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/dashboard'
    | '/challenges/$id'
    | '/challenges/new'
    | '/dashboard/citizen'
    | '/government/dashboard'
    | '/industry/dashboard'
    | '/issues/$id'
    | '/university/dashboard'
    | '/worker/dashboard'
    | '/challenges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/dashboard'
    | '/challenges/$id'
    | '/challenges/new'
    | '/dashboard/citizen'
    | '/government/dashboard'
    | '/industry/dashboard'
    | '/issues/$id'
    | '/university/dashboard'
    | '/worker/dashboard'
    | '/challenges'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/dashboard'
    | '/challenges/$id'
    | '/challenges/new'
    | '/dashboard/citizen'
    | '/government/dashboard'
    | '/industry/dashboard'
    | '/issues/$id'
    | '/university/dashboard'
    | '/worker/dashboard'
    | '/challenges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  ChallengesIdRoute: typeof ChallengesIdRoute
  ChallengesNewRoute: typeof ChallengesNewRoute
  DashboardCitizenRoute: typeof DashboardCitizenRoute
  GovernmentDashboardRoute: typeof GovernmentDashboardRoute
  IndustryDashboardRoute: typeof IndustryDashboardRoute
  IssuesIdRoute: typeof IssuesIdRoute
  UniversityDashboardRoute: typeof UniversityDashboardRoute
  WorkerDashboardRoute: typeof WorkerDashboardRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id': {
      id: '/challenges/$id'
      path: '/challenges/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof ChallengesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/new': {
      id: '/challenges/new'
      path: '/challenges/new'
      fullPath: '/challenges/new'
      preLoaderRoute: typeof ChallengesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/citizen': {
      id: '/dashboard/citizen'
      path: '/dashboard/citizen'
      fullPath: '/dashboard/citizen'
      preLoaderRoute: typeof DashboardCitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government/dashboard': {
      id: '/government/dashboard'
      path: '/government/dashboard'
      fullPath: '/government/dashboard'
      preLoaderRoute: typeof GovernmentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/dashboard': {
      id: '/industry/dashboard'
      path: '/industry/dashboard'
      fullPath: '/industry/dashboard'
      preLoaderRoute: typeof IndustryDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$id': {
      id: '/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof IssuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/dashboard': {
      id: '/university/dashboard'
      path: '/university/dashboard'
      fullPath: '/university/dashboard'
      preLoaderRoute: typeof UniversityDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/dashboard': {
      id: '/worker/dashboard'
      path: '/worker/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof WorkerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  ChallengesIdRoute: ChallengesIdRoute,
  ChallengesNewRoute: ChallengesNewRoute,
  DashboardCitizenRoute: DashboardCitizenRoute,
  GovernmentDashboardRoute: GovernmentDashboardRoute,
  IndustryDashboardRoute: IndustryDashboardRoute,
  IssuesIdRoute: IssuesIdRoute,
  UniversityDashboardRoute: UniversityDashboardRoute,
  WorkerDashboardRoute: WorkerDashboardRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
